# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "[#](blue) [$all](dimmed)"
continuation_prompt = "[â—](dimmed purple) "

[character]
success_symbol = '[â—](green)'
error_symbol = '[â—Œ](red)'

[username]
show_always = true
style_user = "green bold"
format = '([$user]($style) )'
aliases = { feraxhp = "" }

[directory]
style = "yellow bold"

[git_branch]
style = "bold cyan"
only_attached = true

[git_status]
disabled = false
format = "([{ $staged$renamed$modified$untracked$deleted$typechanged$conflicted$stashed}]($style) )"

diverged = "â‡•"
ahead = "â‡¡"
behind = "â‡£"
up_to_date = ""

modified = "[* ](yellow)"
# renamed = "[â— ](yellow)"
renamed = ""

conflicted = ""
typechanged = ""

staged = "[â—‰ ](green)"
stashed = ""

untracked = "[â‡ ](red)"
# deleted = "[â—Œ ](bold red)"
deleted = ""
style = "blue"

ignore_submodules = false
use_git_executable = false

[git_commit]
format = "on [î‚  \\($hash$tag\\)]($style)"
tag_disabled = false
style = "green cyan"

[git_state]
disabled = false
cherry_pick = '[ğŸ’ PICKING](bold red)'
merge = '[ğŸ¥£ MERGING](bold yellow)'